CREATE TYPE starRating AS ENUM ('1','2','3','4','5');

CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title NOT NULL,
  url NOT NULL,
  rating starRating NOT NULL,
  description TEXT
)